-- Community + Admin tooling tables
-- Run this in the Supabase SQL editor.

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_by uuid not null references public.users(uid) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_uid uuid not null references public.users(uid) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (team_id, user_uid)
);

create table if not exists public.team_challenges (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  title text not null,
  description text,
  due_date date,
  created_by uuid not null references public.users(uid) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.team_challenge_submissions (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.team_challenges(id) on delete cascade,
  user_uid uuid not null references public.users(uid) on delete cascade,
  note text not null,
  submitted_at timestamptz not null default now(),
  unique (challenge_id, user_uid)
);

create index if not exists idx_team_members_team_id on public.team_members(team_id);
create index if not exists idx_team_members_user_uid on public.team_members(user_uid);
create index if not exists idx_team_challenges_team_id on public.team_challenges(team_id);
create index if not exists idx_team_challenge_submissions_challenge_id on public.team_challenge_submissions(challenge_id);
create index if not exists idx_team_challenge_submissions_user_uid on public.team_challenge_submissions(user_uid);

alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.team_challenges enable row level security;
alter table public.team_challenge_submissions enable row level security;

-- Teams policies
create policy "Teams can be viewed by authenticated users"
  on public.teams for select
  using (auth.role() = 'authenticated');

create policy "Team creator can create team"
  on public.teams for insert
  with check (auth.uid() = created_by);

create policy "Team creator can update team"
  on public.teams for update
  using (auth.uid() = created_by);

create policy "Team creator can delete team"
  on public.teams for delete
  using (auth.uid() = created_by);

-- Team members policies
create policy "Team members can be viewed by authenticated users"
  on public.team_members for select
  using (auth.role() = 'authenticated');

create policy "Users can join themselves"
  on public.team_members for insert
  with check (auth.uid() = user_uid);

create policy "Users can leave themselves"
  on public.team_members for delete
  using (auth.uid() = user_uid);

-- Team challenges policies
create policy "Team challenges visible to authenticated users"
  on public.team_challenges for select
  using (auth.role() = 'authenticated');

create policy "Team challenge creator can create"
  on public.team_challenges for insert
  with check (auth.uid() = created_by);

create policy "Team challenge creator can update"
  on public.team_challenges for update
  using (auth.uid() = created_by);

create policy "Team challenge creator can delete"
  on public.team_challenges for delete
  using (auth.uid() = created_by);

-- Team challenge submissions policies
create policy "Team submissions visible to authenticated users"
  on public.team_challenge_submissions for select
  using (auth.role() = 'authenticated');

create policy "Users can submit for themselves"
  on public.team_challenge_submissions for insert
  with check (auth.uid() = user_uid);

create policy "Users can update their submission"
  on public.team_challenge_submissions for update
  using (auth.uid() = user_uid);

create policy "Users can delete their submission"
  on public.team_challenge_submissions for delete
  using (auth.uid() = user_uid);
